# Generated by Django 3.0.5 on 2020-05-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='biliUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buser', models.CharField(max_length=255, unique=True, verbose_name='账号')),
                ('bpw', models.CharField(max_length=255, unique=True, verbose_name='密码')),
            ],
            options={
                'verbose_name': 'B站账号信息',
                'verbose_name_plural': 'B站账号信息',
                'db_table': 'biliUser',
            },
        ),
    ]
